# Generated by Django 5.0.6 on 2024-06-14 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_image'),
        ('lessons', '0003_alter_lessons_options'),
        ('users', '0003_alter_payments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payed_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='оплаченный курс'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payed_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lessons', verbose_name='оплаченный урок'),
        ),
    ]
