# Generated by Django 5.0.6 on 2024-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='value',
        ),
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
        migrations.AddField(
            model_name='payments',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ID сессии'),
        ),
    ]
