# Generated by Django 5.0.6 on 2024-06-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessons_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
    ]
